clippy_task:
    container:
        image: rust:latest
    component_script: rustup component add clippy
    toolchain_cache:
        folder: $RUSTUP_HOME
        fingerprint_script: rustc --version
    cargo_cache:
        folder: $CARGO_HOME/registry
        fingerprint_script: cat Cargo.lock
    deps_script: apt-get update && apt-get install -y libsdl2-dev libsdl2-mixer-dev && apt-get clean
    fmt_script: cargo clippy

rustfmt_task:
    container:
        image: rustlang/rust:nightly
    component_script: rustup component add rustfmt
    fmt_script: cargo fmt --all -- --check

linux_task:
    container:
      image: rust:latest
    matrix:
        - env:
              RUSTVER: stable
        - allow_failures: true
          env:
              RUSTVER: nightly
    rustup_script: rustup toolchain install $RUSTVER
    toolchain_cache:
        folder: $RUSTUP_HOME
        fingerprint_script: rustc +$RUSTVER --version
    cargo_cache:
        folder: $CARGO_HOME/registry
        fingerprint_script: cat Cargo.lock
    deps_script: apt-get update && apt-get install -y libsdl2-dev libsdl2-mixer-dev && apt-get clean
    build_script: cargo +$RUSTVER build
    test_script: cargo +$RUSTVER test
    before_cache_script: rm -rf $CARGO_HOME/registry/index
