[package]
name = "gunroar"
version = "0.1.0"
authors = ["Ben Boeckel <mathstuf@gmail.com>"]
readme = "README.md"
license = "BSD-2-Clause"

[dependencies]
#abagames-util = "~0.1"
cgmath = "~0.12"
clap = "~2.19"
gfx = { git = "https://github.com/gfx-rs/gfx" }
image = { version = "~0.10", default-features = false, features = ["bmp"] }
itertools = "~0.5"
log = "~0.3"
sdl2 = "~0.27"

[dependencies.abagames-util]
path = "../../rust-abagames-util/src"
