set(CMAKE_D_DASH_O "-o")
set(CMAKE_BASE_NAME ldc)

set(CMAKE_STATIC_LIBRARY_CREATE_D_FLAGS "-lib")

set(CMAKE_SHARED_LIBRARY_D_FLAGS "-fPIC")
set(CMAKE_SHARED_LIBRARY_CREATE_D_FLAGS "-shared")
set(CMAKE_SHARED_LIBRARY_LINK_D_FLAGS "-rdynamic")
set(CMAKE_SHARED_LIBRARY_SONAME_D_FLAG "-Wl,-soname,")
set(CMAKE_SHARED_LIBRARY_RUNTIME_D_FLAG "-Wl,-rpath,")
set(CMAKE_SHARED_LIBRARY_RUNTIME_D_FLAG_SEP ":")
set(CMAKE_INCLUDE_FLAG_D "-I")
set(CMAKE_INCLUDE_FLAG_D_SEP "") # , or empty
set(CMAKE_LIBRARY_PATH_FLAG "-L")
set(CMAKE_LIBRARY_PATH_TERMINATOR "") # for the Digital Mars D compiler the link paths have to be terminated with a "/"
set(CMAKE_LINK_LIBRARY_FLAG "-l")

set(CMAKE_LINK_LIBRARY_SUFFIX "")
set(CMAKE_STATIC_LIBRARY_PREFIX "lib")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".a")
set(CMAKE_SHARED_LIBRARY_PREFIX "lib") # lib
set(CMAKE_SHARED_LIBRARY_SUFFIX ".so") # .so
set(CMAKE_EXECUTABLE_SUFFIX "") # .exe

set(CMAKE_FIND_LIBRARY_PREFIXES "lib")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".so" ".a")

set(CMAKE_D_FLAGS_INIT "")
set(CMAKE_D_LINK_FLAGS "")
set(CMAKE_D_FLAGS_DEBUG_INIT "-g")
set(CMAKE_D_FLAGS_MINSIZEREL_INIT "-Os")
set(CMAKE_D_FLAGS_RELEASE_INIT "-O3")
set(CMAKE_D_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")
set(CMAKE_D_CREATE_PREPROCESSED_SOURCE "<CMAKE_D_COMPILER> <FLAGS> -E <SOURCE> > <PREPROCESSED_SOURCE>")
set(CMAKE_D_CREATE_ASSEMBLY_SOURCE "<CMAKE_D_COMPILER> <DEFINES> <FLAGS> -S <SOURCE> -o <ASSEMBLY_SOURCE>")
#set(CMAKE_INCLUDE_SYSTEM_FLAG_D "-isystem -I")
set(CMAKE_DEPFILE_FLAGS_D "-MMD -MT <OBJECT> -MF <DEPFILE>")
set(CMAKE_NINJA_DEPTYPE_D "gcc")
set(CMAKE_D_COMPILE_OPTIONS_PIC "-fPIC")
set(CMAKE_D_COMPILE_OPTIONS_PIE "-pie")

set(CMAKE_D_COMPILE_OBJECT
    "<CMAKE_D_COMPILER> <DEFINES> <FLAGS> -o <OBJECT> -c <SOURCE>")
set(CMAKE_D_CREATE_SHARED_LIBRARY
    "<CMAKE_D_COMPILER> <CMAKE_SHARED_LIBRARY_D_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_D_FLAGS> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
set(CMAKE_D_LINK_EXECUTABLE
    "<CMAKE_D_COMPILER> <FLAGS> <CMAKE_D_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
